{% set name = "typhos" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7a4122e2ddf38b7fb9a4cafe0e7057f2019ef2d4e8416d7f16d7de650274b0b6

build:
  number: 0
  noarch: python
  entry_points:
    - typhos = typhos.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - coloredlogs
    - entrypoints
    - numpy
    - numpydoc
    - ophyd >=1.5.0
    - pcdsutils
    - pydm
    - pyqt >=5
    - pyqtgraph
    - qdarkstyle
    - qtawesome
    - qtconsole
    - qtpy
    - timechart >=1.2.4

test:
  imports:
    - typhos
    - typhos.cli
  commands:
    - typhos --help

about:
  home: https://github.com/pcdshub/typhos
  doc_url: https://pcdshub.github.io/typhos
  dev_url: https://github.com/pcdshub/typhos
  summary: Automatic-yet-customizable Graphical User Interface Generation for Ophyd Devices
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - klauer
    - zllentz
    - zrylettc
