{% set name = "typhos" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: bca00d1097195c7eec1b3377be4aec2d2e59cfa77c366e81d20dbbbc01bb9a25

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - typhos = typhos.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - coloredlogs
    - entrypoints
    - numpy
    - numpydoc
    - ophyd >=1.5.0
    - pcdsutils
    - pyqt =5
    - platformdirs
    - pydm >=1.19.1
    - pyqtgraph
    - pyyaml
    - qdarkstyle
    - qtawesome
    - qtpy
    - timechart >=1.2.4
  run_constrained:
    - happi >=1.14.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - typhos
    - typhos.cli
  commands:
    - typhos --help

about:
  home: https://github.com/pcdshub/typhos
  doc_url: https://pcdshub.github.io/typhos
  dev_url: https://github.com/pcdshub/typhos
  summary: Automatic-yet-customizable Graphical User Interface Generation for Ophyd Devices
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
