{% set name = "typhos" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fc4ed75b11811fed53c0ffbbe46cfeff3522eaa936f1cd868cb964369539818c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - typhos = typhos.cli:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - coloredlogs
    - entrypoints
    - numpy
    - numpydoc
    - ophyd >=1.5.0
    - pcdsutils
    - pydm >=1.16.0
    - pyqt >=5
    - pyqtgraph
    - qdarkstyle
    - qtawesome
    - qtconsole
    - qtpy
    - timechart >=1.2.4
  run_constrained:
    - happi >=1.14.0

test:
  imports:
    - typhos
    - typhos.cli
  commands:
    - typhos --help

about:
  home: https://github.com/pcdshub/typhos
  doc_url: https://pcdshub.github.io/typhos
  dev_url: https://github.com/pcdshub/typhos
  summary: Automatic-yet-customizable Graphical User Interface Generation for Ophyd Devices
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
    - klauer
    - tangkong
    - zllentz
