{% set name = "typhos" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 26276a2dcef6101b810d302ae393cd3905a424793736de031f3281faeb7abd95

build:
  number: 0
  noarch: python
  entry_points:
    - typhos = typhos.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pyqt >=5
    - qtpy
    - coloredlogs
    - numpy
    - numpydoc
    - ophyd >=1.5.0
    - pcdsutils
    - pydm
    - pyqtgraph
    - qdarkstyle
    - qtawesome
    - qtconsole
    - timechart

test:
  imports:
    - typhos
    - typhos.cli
  commands:
    - typhos --help

about:
  home: https://github.com/pcdshub/typhos
  doc_url: https://pcdshub.github.io/typhos
  dev_url: https://github.com/pcdshub/typhos
  summary: Automatic-yet-customizable Graphical User Interface Generation for Ophyd Devices
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - klauer
    - zllentz
    - zrylettc
