{% set name = "typhos" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 56a002dd9b9f09c78fe5c8482cd9d4ff124cb3b3ef178c6e5ec49063ae811d41

build:
  number: 0
  noarch: python
  entry_points:
    - typhos = typhos.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyqt >=5
    - qtpy
    - coloredlogs
    - numpy
    - numpydoc
    - ophyd >=1.5.0
    - pcdsutils
    - pydm
    - pyqtgraph
    - qdarkstyle
    - qtawesome
    - qtconsole
    - timechart

test:
  imports:
    - typhos
    - typhos.cli
  commands:
    - typhos --help

about:
  home: https://github.com/pcdshub/typhos
  doc_url: https://pcdshub.github.io/typhos
  dev_url: https://github.com/pcdshub/typhos
  summary: Automatic-yet-customizable Graphical User Interface Generation for Ophyd Devices
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - klauer
    - hhslepicka
    - zllentz
